using './main.bicep'

param logAnalyticsWorkspaceName = 'de7e6bce-3d56-4e0e-aa5e-0a4104de013f-RG-PlataformaTechRid-ESC'
param applicationInsightsName = 'appinsight-tetxito'
param appServicePlanName = 'ASP-RGPlataformaTechRiders-9a12'
param webAppName = 'apitetxito'
param sqlServerName = 'techriders'
param sqlDatabaseName = 'TechRidersDB'
param storageAccountName = 'storagetetxito'
param staticWebAppName = 'techito'
