FROM node:22-alpine AS build
WORKDIR /app

COPY techito/package*.json ./
RUN npm ci

COPY techito/. ./
RUN npm run build

FROM nginx:1.27-alpine AS runtime
WORKDIR /usr/share/nginx/html

COPY techito/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/techito/browser ./

EXPOSE 80
