FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY backend/TechRiders.API/TechRiders.Api.csproj backend/TechRiders.API/
COPY backend/TechRiders.Application/TechRiders.Application.csproj backend/TechRiders.Application/
COPY backend/TechRiders.Domain/TechRiders.Domain.csproj backend/TechRiders.Domain/
COPY backend/TechRiders.Infrastructure/TechRiders.Infrastructure.csproj backend/TechRiders.Infrastructure/
RUN dotnet restore backend/TechRiders.API/TechRiders.Api.csproj

COPY backend/. backend/
RUN dotnet publish backend/TechRiders.API/TechRiders.Api.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "TechRiders.Api.dll"]
